apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  credentials:
    secretRef:
      key: creds.json
      name: gcp-credentials
      namespace: crossplane-system
    source: Secret
  projectID: ace-gdg-cloud
