apiVersion: storage.gcp.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: crossplane-example-bucket-F338F23D
  name: crossplane-example-bucket-F338F23D
spec:
  forProvider:
    deletionPolicy: Delete
    location: EU
    storageClass: MULTI_REGIONAL
