apiVersion: storage.gcp.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: crossplane-example-bucket-e48be51a
  name: crossplane-example-bucket-e48be51a
spec:
  forProvider:
    location: EU
    storageClass: MULTI_REGIONAL
