apiVersion: storage.gcp.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: devopstr-crossplane-24-94b5c8c6
  name: devopstr-crossplane-24-94b5c8c6
spec:
  forProvider:
    location: EU
    storageClass: MULTI_REGIONAL
