apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.12.6
- namespace.yaml

## changes to config maps
patches:
- path: crossplane-installation-patches.yaml

namespace: argocd